version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/codicefun-blog-api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/codicefun-blog-app"
    schedule:
      interval: "weekly"
