name: Build API with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  JJWT_EXPIRE: 604800000
  JJWT_SECRET: "src/main/java/com/codicefun/blog/util/JwtUtil"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package
        working-directory: codicefun-blog-api
