name: Build API with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  JJWT_EXPIRE: 604800000
  JJWT_SECRET: "src/main/java/com/codicefun/blog/util/JwtUtil"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17, 21 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: 'codicefun-blog-api/pom.xml'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
